{
    "openapi": "3.0.0",
    "info": {
      "title": "Capsbooks",
      "description": "This is a sample server for a book store.",
      "contact": {
        "name": "API Support",
        "url": "http://www.example.com/support",
        "email": "support@example.com"
      },
      "version": "1.0.1"
    },
  
    "servers": [
      {
        "url": "https://capsbook.herokuapp.com/api-documentation",
        "description": "deploy"
      },
      {
        "url": "http://localhost:3000/api-documentation",
        "description": "test"
      }
    ],
    "paths": {
      "/user": {
        "post": {
          "description": "Essa rota é responsavel por cadastrar um usuário.",
          "tags": ["User"],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/UserReq" },
                "examples": {
                  "Example": {
                    "value": {
                      "name": "Patrick Nekel",
                      "email": "nekeldev@gmail.com",
                      "password": "1234",
                      "is_adm": false
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "409": {
              "description": "Email already exists"
            },
            "201": {
              "description": "Created",
               "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/UserRes" },
                  "examples": {
                    "Example": {
                      "value": {
                        "name": "Patrick Nekel",
                        "email": "nekeldev@gmail.com",
                        "is_adm": false,
                        "created_at": "2022-01-25T02:13:05.384Z",
	                      "updated_at": "2022-01-25T02:13:05.384Z"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "get": {
          "description": "Essa rota é responsavel por listar todos os usuários. Apenas usuários admin podem acessar essa rota.",
          "tags": ["User"],
          "requestBody": {
            "content": {
              "application/json": {
              }
            }
          },
          "responses": {
            "401": {
              "description": "Unauthorized"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/UserList" },
                  "examples": {
                    "Example": {
                      "value": [{
                        "name": "Patrick Nekel",
                        "email": "nekeldev@gmail.com",
                        "is_adm": false,
                        "created_at": "2022-01-25T02:13:05.384Z",
	                      "updated_at": "2022-01-25T02:13:05.384Z"
                      }]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/login": {
        "post": {
          "description": "Essa rota é responsavel por autenticar um usuário.",
          "tags": ["Login"],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/SessionReq" },
                "examples": {
                  "Example": {
                    "value": {
                      "email": "nekeldev@gmail.com",
                      "password": "1234"
                    }
                  }
                }
              }
            }              
          },
          "responses": {
            "401": {
              "description": "Incorrect email / password combination"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/SessionRes" },
                  "examples": {
                    "Response": {
                      "value": {
                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDMxMjg5MDUsImV4cCI6MTY0MzIxNTMwNSwic3ViIjoiNTgyZGFiODYtMDIyZi00MWZkLTg0NmQtMWY5ODExZTQyMTExIn0.O17q9vUY2q9nMU3Fs7ZdOUdAELwpXhqZhDx0Kfj2tOs"                       
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/user/profile": {
        "get": {
          "description": "Essa rota é responsavel por listar as informações do usuário logado. Precisa de autenticação.",
          "tags": ["User"],
          "requestBody": {
            "content": {
              "application/json": {                
              }
            }   
          },
          "responses": {
            "404": {
              "description": "User not found"
            },
            "401": {
              "description": "Missing authorization headers, Invalid Token"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/UserRes" },
                  "examples": {
                    "Example": {
                      "value": {
                        "name": "Patrick Nekel",
                        "email": "nekeldev@gmail.com",
                        "is_adm": false,
                        "created_at": "2022-01-25T02:13:05.384Z",
	                      "updated_at": "2022-01-25T02:13:05.384Z"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/user/{id}": {      
        "patch": {
          "description": "Essa rota é responsavel por atualizar um usuário específico. Precisa de autenticação. Um usuário não admin pode buscar apenas seu próprio usuário.",
          "tags": ["User"],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/UserReq" },
                "examples": {
                  "Example": {
                    "value": {
                      "name": "Patrick Nekel Jr",
                      "email": "nekeldev@yahoo.com",
                      "password": "123456"
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "404": {
              "description": "User not found"
            },
            "401": {
              "description": "Missing authorization headers, Invalid Token, Missing admin permissions"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/UserRes" },
                  "examples": {
                    "Example": {
                      "value": {
                        "name": "Patrick Nekel Jr",
                        "email": "nekeldev@yahoo.com",
                        "is_adm": false,
                        "created_at": "2022-01-25T02:13:05.384Z",
	                      "updated_at": "2022-01-26T02:13:05.384Z"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "delete": {
          "description": "Essa rota é responsavel por excluir um usuário específico. Precisa de autenticação. Um usuário não admin pode buscar apenas seu próprio usuário.",
          "tags": ["User"],
          "requestBody": {
            "content": {
              "application/json": {               
              }
            }
          },
          "responses": {
            "404": {
              "description": "User not found"
            },
            "401": {
              "description": "Missing authorization headers, Invalid Token, Missing admin permissions"
            },
            "204": {
              "description": "No Content",
              "content": {
                "application/json": {                 
                }
              }
            }
          }
        }
      },            
      "/book": {
        "post": {
          "description": "Essa rota é responsavel por cadastrar um livro. Precisa de autenticação. Apenas usuários admin têm acesso a esse endpoint.",
          "tags": ["Book"],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/BookReq" },
                "examples": {
                  "Example": {
                    "value": {
                      "name": "A História da Programação",
                      "price": 30.49,
                      "description": "Excelente livro.",
                      "author": "Peter Jr"
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "401": {
              "description": "Missing authorization headers, Invalid Token, Unauthorized. Only admin has access to this endpoint."
            },
            "201": {
              "description": "Created",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/BookRes" },
                  "examples": {
                    "Example": {
                      "value": {
                        "id": "62768994-1af1-469a-a305-66fb1056a1a1",
                        "name": "A História da Programação",
                        "price": 30.49,
                        "description": "Excelente livro.",
                        "author": "Peter Jr",
                        "created_at": "2022-01-25T02:13:05.384Z",
	                      "updated_at": "2022-01-26T02:13:05.384Z"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "get": {
          "description": "Essa rota é responsavel por listar todos os livros. É possível filtrar por título e/ou autor. Qualquer pessoa tem acesso a esse endpoint (não precisa estar autenticado).",
          "tags": ["Book"],
          "requestBody": {
            "content": {
              "application/json": {
              }            
            }
          },
          "responses": {
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/BookList" },
                  "examples": {
                    "Example": {
                      "value": [{
                        "id": "62768994-1af1-469a-a305-66fb1056a1a1",
                        "name": "A História da Programação",
                        "price": 30.49,
                        "description": "Excelente livro.",
                        "author": "Peter Jr",
                        "created_at": "2022-01-25T02:13:05.384Z",
	                      "updated_at": "2022-01-26T02:13:05.384Z"
                      }]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/book/{id}": {
        "get": {
          "description": "Essa rota é responsavel por listar um livro específico. Qualquer pessoa tem acesso a esse endpoint (não precisa estar autenticado).",
          "tags": ["Book"],
          "requestBody": {
            "content": {
              "application/json": {                
              }
            }   
          },
          "responses": {
            "404": {
              "description": "Book not found"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/BookRes" },
                  "examples": {
                    "Example": {
                      "value": {
                        "id": "62768994-1af1-469a-a305-66fb1056a1a1",
                        "name": "A História da Programação",
                        "price": 30.49,
                        "description": "Excelente livro.",
                        "author": "Peter Jr",
                        "created_at": "2022-01-25T02:13:05.384Z",
	                      "updated_at": "2022-01-26T02:13:05.384Z"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "patch": {
          "description": "Essa rota é responsavel por atualizar um livro específico. Precisa de autenticação. Apenas um usuário admin tem acesso a essa rota.",
          "tags": ["Book"],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/BookReq" },
                "examples": {
                  "Patrick": {
                    "value": {
                      "price": 40.49
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "404": {
              "description": "Book not found"
            },
            "401": {
              "description": "Missing authorization headers, Invalid Token, Unauthorized. Only admin has access to this endpoint."
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/BookRes" },
                  "examples": {
                    "Example": {
                      "value": {
                        "id": "62768994-1af1-469a-a305-66fb1056a1a1",
                        "name": "A História da Programação",
                        "price": 40.49,
                        "description": "Excelente livro.",
                        "author": "Peter Jr",
                        "created_at": "2022-01-25T02:13:05.384Z",
	                      "updated_at": "2022-01-26T02:13:05.384Z"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "delete": {
          "description": "Essa rota é responsavel por excluir um livro específico. Precisa de autenticação. Apenas um usuário admin tem acesso a essa rota.",
          "tags": ["Book"],
          "requestBody": {
            "content": {
              "application/json": {               
              }
            }
          },
          "responses": {
            "404": {
              "description": "Book not found"
            },
            "401": {
              "description": "Missing authorization headers, Invalid Token, Unauthorized. Only admin has access to this endpoint."
            },
            "204": {
              "description": "No Content",
              "content": {
                "application/json": {                 
                }
              }
            }
          }
        }
      }, 
      "/cart": {
        "post": {
          "description": "Essa rota é responsavel por colocar um produto no carrinho. Precisa de autenticação. Qualquer usuário autenticado tem acesso a esse endpoint.",
          "tags": ["Cart"],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/CartAndBuyReq" },
                "examples": {
                  "Example": {
                    "value": {
                      "books_ids": ["455dd9ea-f4e3-4bf3-8150-ef2ebe9097c2"]
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "401": {
              "description": "Missing authorization headers, Invalid Token"
            },
            "400": {
              "description": "Invalid list of books"
            },
            "201": {
              "description": "Ok",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/CartAndBuyRes" },
                  "examples": {
                    "Example": {
                      "value": {
                        "id": "66fc31be-9553-42ed-97df-e2d53e6ae19e",
                        "userId": "582dab86-022f-41fd-846d-1f9811e42111",
                        "books": [
                          {
                            "id": "588a8d31-9bda-4f51-af9f-e8ec1e3b4472",
                            "created_at": "2022-01-26T18:01:52.904Z",
                            "book": {
                              "id": "92b92266-d92e-4fea-bbe0-d56d49c7e93f",
                              "title": "O grande livro de Futebol 3",
                              "author": "John 4",
                              "description": "O jogo",
                              "price": "10.49",
                              "created_at": "2022-01-26T01:07:16.616Z",
                              "updated_at": "2022-01-26T01:07:16.616Z"    
                            }
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "get": {
          "description": "Essa rota é responsavel por listar todos os carrinhos. Precisa de autenticação. Apenas usuários admin têm acesso a esse endpoint.",
          "tags": ["Cart"],
          "requestBody": {
            "content": {
              "application/json": {
              }             
            }
          },
          "responses": {
            "401": {
              "description": "Missing authorization headers, Invalid Token, Unauthorized. Only admin has access to this endpoint."
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/CartAndBuyList" },
                  "examples": {
                    "Example": {
                      "value": [{
                        "id": "66fc31be-9553-42ed-97df-e2d53e6ae19e",
                        "userId": "582dab86-022f-41fd-846d-1f9811e42111",
                        "books": [
                          {
                            "id": "588a8d31-9bda-4f51-af9f-e8ec1e3b4472",
                            "created_at": "2022-01-26T18:01:52.904Z",
                            "book": {
                              "id": "92b92266-d92e-4fea-bbe0-d56d49c7e93f",
                              "title": "O grande livro de Futebol 3",
                              "author": "John 4",
                              "description": "O jogo",
                              "price": "10.49",
                              "created_at": "2022-01-26T01:07:16.616Z",
                              "updated_at": "2022-01-26T01:07:16.616Z"
                            }
                          }
                        ]
                      }]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/cart/{id}": {
        "get": {
          "description": "Essa rota é responsavel por listar um carrinho específico. Precisa de autenticação. Um usuário não admin pode visualizar apenas seu próprio carrinho.",
          "tags": ["Cart"],
          "requestBody": {
            "content": {
              "application/json": {
              }
            }
          },
          "responses": {
            "404": {
              "description": "Cart not found"
            },
            "401": {
              "description": "Missing authorization headers, Invalid Token, Missing admin permissions"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/CartAndBuyRes" },
                  "examples": {
                    "Example": {
                      "value": {
                        "id": "66fc31be-9553-42ed-97df-e2d53e6ae19e",
                        "userId": "582dab86-022f-41fd-846d-1f9811e42111",
                        "books": [
                          {
                            "id": "588a8d31-9bda-4f51-af9f-e8ec1e3b4472",
                            "created_at": "2022-01-26T18:01:52.904Z",
                            "book": {
                              "id": "92b92266-d92e-4fea-bbe0-d56d49c7e93f",
                              "title": "O grande livro de Futebol 3",
                              "author": "John 4",
                              "description": "O jogo",
                              "price": "10.49",
                              "created_at": "2022-01-26T01:07:16.616Z",
                              "updated_at": "2022-01-26T01:07:16.616Z"
                            }
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/cart/{product_id}": {
        "delete": {
          "description": "Essa rota é responsavel por excluir um item de um carrinho específico. Precisa de autenticação. Um usuário não admin só pode excluir itens do seu próprio carrinho.",
          "tags": ["Cart"],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/Email" },
                "examples": {
                  "Example": {
                    "value": {
                      "email": "john@mail.com"
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "404": {
              "description": "User not found, Cart not found, Book not found in store, Book not found in cart"
            },
            "401": {
              "description": "Missing authorization headers, Invalid Token, Missing admin permissions"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/CartAndBuyRes" },
                  "examples": {
                    "Example": {
                      "value": {
                        "id": "66fc31be-9553-42ed-97df-e2d53e6ae19e",
                        "userId": "582dab86-022f-41fd-846d-1f9811e42111",
                        "books": [                          
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/purchase": {
        "post": {
          "description": "Essa rota é responsavel por concluir a compra dos itens que estão no carrinho e envia um email com o custo total da compra. Precisa de autenticação. Qualquer usuário autenticado tem acesso a esse endpoint.",
          "tags": ["Purchase"],
          "requestBody": {
            "content": {
              "application/json": {                
              }              
            }
          },
          "responses": {
            "422": {
              "description": "Cart is empty"
            },
            "404": {
              "description": "No cart was found, Purchase not found"
            },
            "401": {
              "description": "Missing authorization headers, Invalid Token"
            },
            "201": {
              "description": "Ok",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/CartAndBuyRes" },
                  "examples": {
                    "Example": {
                      "value": {
                        "id": "66fc31be-9553-42ed-97df-e2d53e6ae19e",
                        "userId": "582dab86-022f-41fd-846d-1f9811e42111",
                        "books": [
                          {
                            "id": "588a8d31-9bda-4f51-af9f-e8ec1e3b4472",
                            "created_at": "2022-01-26T18:01:52.904Z",
                            "book": {
                              "id": "92b92266-d92e-4fea-bbe0-d56d49c7e93f",
                              "title": "O grande livro de Futebol 3",
                              "author": "John 4",
                              "description": "O jogo",
                              "price": "10.49",
                              "created_at": "2022-01-26T01:07:16.616Z",
                              "updated_at": "2022-01-26T01:07:16.616Z"
                            }
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "get": {
          "description": "Essa rota é responsavel por listar todas as compras. Precisa de autenticação. Usuários não admin conseguem observar apenas suas compras.",
          "tags": ["Purchase"],
          "requestBody": {
            "content": {
              "application/json": {
              }             
            }
          },
          "responses": {
            "401": {
              "description": "Missing authorization headers, Invalid Token"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/CartAndBuyList" },
                  "examples": {
                    "Example": {
                      "value": [{
                        "id": "66fc31be-9553-42ed-97df-e2d53e6ae19e",
                        "userId": "582dab86-022f-41fd-846d-1f9811e42111",
                        "books": [
                          {
                            "id": "588a8d31-9bda-4f51-af9f-e8ec1e3b4472",
                            "created_at": "2022-01-26T18:01:52.904Z",
                            "book": {
                              "id": "92b92266-d92e-4fea-bbe0-d56d49c7e93f",
                              "title": "O grande livro de Futebol 3",
                              "author": "John 4",
                              "description": "O jogo",
                              "price": "10.49",
                              "created_at": "2022-01-26T01:07:16.616Z",
                              "updated_at": "2022-01-26T01:07:16.616Z"
                            }
                          }
                        ]
                      }]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/purchase/{id}": {
        "get": {
          "description": "Essa rota é responsavel por listar uma compra específica. Precisa de autenticação. Um usuário não admin pode visualizar apenas suas próprias compras.",
          "tags": ["Purchase"],
          "requestBody": {
            "content": {
              "application/json": {
              }
            }
          },
          "responses": {
            "404": {
              "description": "Purchase not found"
            },
            "401": {
              "description": "Missing authorization headers, Invalid Token, Missing admin permissions"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/CartAndBuyRes" },
                  "examples": {
                    "Example": {
                      "value": {
                        "id": "66fc31be-9553-42ed-97df-e2d53e6ae19e",
                        "userId": "582dab86-022f-41fd-846d-1f9811e42111",
                        "books": [
                          {
                            "id": "588a8d31-9bda-4f51-af9f-e8ec1e3b4472",
                            "created_at": "2022-01-26T18:01:52.904Z",
                            "book": {
                              "id": "92b92266-d92e-4fea-bbe0-d56d49c7e93f",
                              "title": "O grande livro de Futebol 3",
                              "author": "John 4",
                              "description": "O jogo",
                              "price": "10.49",
                              "created_at": "2022-01-26T01:07:16.616Z",
                              "updated_at": "2022-01-26T01:07:16.616Z"
                            }
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/book/{id}/review": {
        "post": {
          "description": "Essa rota é responsavel por criar uma review. Precisa de autenticação. Qualquer usuário pode criar uma review.",
          "tags": ["Review"],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/ReviewReq" },
                "examples": {
                  "Example": {
                    "value": {
                      "review": 8,
                      "comment": "Um dos melhores livros que li."
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "404": {
              "description": "Usre not found, Book not found"
            },
            "401": {
              "description": "Missing authorization headers, Invalid Token."
            },
            "201": {
              "description": "Created",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/ReviewRes" },
                  "examples": {
                    "Example": {
                      "value": {
                        "id": "62768994-1af1-469a-a305-66fb1056a1a1",
                        "review": 8,
                        "comment": "Um dos melhores livros que li.",
                        "created_at": "2022-01-25T02:13:05.384Z"
                      }
                    }
                  }
                }
              }
            }
          }
        }        
      },
      "/review": {   
        "get": {
          "description": "Essa rota é responsavel por listar todas as reviews. Precisa de autenticação. Apenas um usuário admin tem acesso a esse endpoint.",
          "tags": ["Review"],
          "requestBody": {
            "content": {
              "application/json": {
              }            
            }
          },
          "responses": {
            "401": {
              "description": "Missing authorization headers, Invalid Token, Unauthorized. Only admin has access to this endpoint"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/ReviewList" },
                  "examples": {
                    "Example": {
                      "value": [{
                        "id": "62768994-1af1-469a-a305-66fb1056a1a1",
                        "review": 8,
                        "comment": "Um dos melhores livros que li.",
                        "created_at": "2022-01-25T02:13:05.384Z"
                      }]
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/review/{id}": {
        "get": {
          "description": "Essa rota é responsavel por listar uma review específica. Precisa estar autenticado. Qualquer usuário tem acesso a esse endpoint.",
          "tags": ["Review"],
          "requestBody": {
            "content": {
              "application/json": {                
              }
            }   
          },
          "responses": {
            "404": {
              "description": "Book not found"
            },
            "401": {
              "description": "Missing authorization headers, Invalid Token, Missing admin permissions"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": { "$ref": "#/components/schemas/ReviewRes" },
                  "examples": {
                    "Example": {
                      "value": {
                        "id": "62768994-1af1-469a-a305-66fb1056a1a1",
                        "review": 8,
                        "comment": "Um dos melhores livros que li.",
                        "created_at": "2022-01-25T02:13:05.384Z"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "delete": {
          "description": "Essa rota é responsavel por excluir um livro específico. Precisa de autenticação. Apenas um usuário admin tem acesso a essa rota.",
          "tags": ["Review"],
          "requestBody": {
            "content": {
              "application/json": {               
              }
            }
          },
          "responses": {
            "404": {
              "description": "Review not found"
            },
            "401": {
              "description": "Missing authorization headers, Invalid Token, Missing admin permissions"
            },
            "204": {
              "description": "No Content",
              "content": {
                "application/json": {                 
                }
              }
            }
          }
        }
      },     
      "/recover": {
        "post": {
          "description": "Rota do 'esqueci senha'. Envia um email para o usuário com um token para ser usado na rota para cadastrar nova senha.",
          "tags": ["Mailer"],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/Email" },
                "examples": {
                  "Example": {
                    "value": {
                      "email": "john@amail.com"
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "404": {
              "description": "User not found"
            },
            "200": {
              "description": "OK",
              "content": {
              }
            }
          }
        }
      },
      "/change_password": {
        "post": {
          "description": "Rota para cadastrar nova senha. Usa um token de validação recebido por email no header.",
          "tags": ["Mailer"],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": { "$ref": "#/components/schemas/NovaSenha" },
                "examples": {
                  "Example": {
                    "value": {
                      "email": "john@amail.com",
                      "password": "12345678"
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "404": {
              "description": "User not found"
            },
            "400": {
              "description": "Invalid token, Token expired; generate a new one"
            },
            "200": {
              "description": "OK",
              "content": {
              }
            }
          }
        }
      }                
    },
    "components": {
      "schemas": {
        "UserReq": {  
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "password": {
              "type": "string"
            },
            "is_adm": {
              "type": "boolean"
            }
          }          
        },
        "UserRes": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "is_adm": {
              "type": "boolean"
            },
            "created_at": {
              "type": "timestamp"
            },
            "updated_at": {
              "type": "timestamp"
            }
          }
        },
        "UserList": {
            "type": "User[]",
            "properties": {
              "name": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "is_adm": {
                "type": "boolean"
              },
              "created_at": {
                "type": "timestamp"
              },
              "updated_at": {
                "type": "timestamp"
              }
    
          }
        },
        "SessionReq": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string"
            },
            "password": {
              "type": "string"
            }
          }
        },
        "SessionRes": {
          "type": "object",
          "properties": {
            "token": {
             "type": "string"
            }
          }
        },
        "BookReq": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "price": {
              "type": "number"
            },
            "description": {
              "type": "string"
            },
            "author": {
              "type": "string"
            }
          }
        },
        "BookRes": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "price": {
              "type": "number"
            },
            "description": {
              "type": "string"
            },
            "author": {
              "type": "string"
            },
            "created_at": {
              "type": "timestamp"
            },
            "updated_at": {
              "type": "timestamp"
            }
          }
        },
        "BookList": {
          "type": "BookRes[]",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "price": {
              "type": "number"
            },
            "description": {
              "type": "string"
            },
            "author": {
              "type": "string"
            },
            "created_at": {
              "type": "timestamp"
            },
            "updated_at": {
              "type": "timestamp"
            }
          }
        },
        "Books": {
          "type":"object",
          "properties": {
            "id": {
              "type": "string"
            },
            "created_at": {
              "type": "timestamp"
            },
            "book": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "price": {
                  "type": "number"
                },
                "description": {
                  "type": "string"
                },
                "author": {
                  "type": "string"
                },
                "created_at": {
                  "type": "timestamp"
                },
                "updated_at": {
                  "type": "timestamp"
                }
              }
            }
          }
        },
        "CartAndBuyReq": {
          "type": "object",
          "properties": {
            "books_ids": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        },
        "CartAndBuyRes": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "userId": {
              "type": "string"
            },
            "books": {
              "type":"Books[]",
              "properties": {
                "id": {
                  "type": "string"
                },
                "created_at": {
                  "type": "timestamp"
                },
                "book": {
                  "type": "BookRes",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "price": {
                      "type": "number"
                    },
                    "description": {
                      "type": "string"
                    },
                    "author": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "timestamp"
                    },
                    "updated_at": {
                      "type": "timestamp"
                    }
                  }
                }
              }
            }
          }
        },
        "CartAndBuyList": {
          "type": "object[]",
          "properties": {
            "id": {
              "type": "string"
            },
            "userId": {
              "type": "string"
            },
            "books": {
              "type": "object[]",
              "properties": {
                "id": {
                  "type": "string"
                },
                "created_at": {
                  "type": "timestamp"
                },
                "book": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "price": {
                      "type": "number"
                    },
                    "description": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "timestamp"
                    },
                    "updated_at": {
                      "type": "timestamp"
                    }
                  }
                }
              }
            }
          }
        },
        "ReviewReq": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "review": {
              "type": "number"
            },
            "comment": {
              "type": "string"
            }
          }
        },
        "ReviewRes": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "review": {
              "type": "number"
            },
            "comment": {
              "type": "string"
            },
            "created_at": {
              "type": "timestamp"
            }
          }
        },
        "ReviewList": {
          "type": "ReviewRes[]",
          "properties": {
            "id": {
              "type": "string"
            },
            "review": {
              "type": "number"
            },
            "comment": {
              "type": "string"
            },
            "created_at": {
              "type": "timestamp"
            }
          }
        },
        "Email": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string"
            }            
          }
        },
        "NovaSenha": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string"
            },
            "password": {
              "type": "string"
            }           
          }
        }
      }
    }
  } 